name: quantities

description: Physical quantities and units.

version: 0.0.2

homepage: https://github.com/mhmdanas/quantities

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0
  tuple: ^2.0.0

dev_dependencies:
  lint: ^1.5.2
  test: ^1.16.5
